# Generated by Django 4.2 on 2023-05-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dest_image', models.ImageField(upload_to='uploads')),
                ('location', models.TextField(max_length=50)),
                ('pack_image', models.ImageField(upload_to='uploads/')),
                ('max_people', models.IntegerField()),
                ('duration', models.CharField(choices=[('1/1', '1 Day and 1 Night'), ('1/2', '1 Day and 2 Night'), ('2/2', '2 Day and 2 Night')], default='1/1', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pack_desc_image', models.ImageField(upload_to='uploads/')),
                ('pack_description', models.TextField()),
                ('pack_includes', models.TextField()),
                ('pack_services', models.TextField()),
            ],
        ),
    ]
