# Generated by Django 4.2 on 2023-05-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='max_people',
            field=models.IntegerField(default=10),
        ),
    ]
