# Generated by Django 4.2 on 2023-05-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_package_location_alter_package_max_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('alternate_tag', models.CharField(default='Gallery Image', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slide_Show_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slideshow/')),
                ('alternate_tag', models.CharField(default='Slide Show Image', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='dest_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.CharField(choices=[('1D/1N', '1 Day and 1 Night'), ('1D/2N', '1 Day and 2 Night'), ('2D/2N', '2 Day and 2 Night')], default='1/1', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
